version: '3.4'
name: rent_and_delivery

networks:
    rent-network:
        driver:
          bridge

services:
    postgres:
        container_name: PostgresDb
        ports:
            - 5455:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_DB=RentAndDelivery
        image: postgres
        networks:
            - rent-network
        volumes:
          - c:\dados\volumes\postgresql:/var/lib/postgresql/data

    pgadmin4:
        container_name: pgAdminDB
        ports:
            - 15432:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=danilo@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=postgres
        image: dpage/pgadmin4
        networks:
            - rent-network
        depends_on:
          - postgres


